### PR TITLE
Adds more templates

### PR DESCRIPTION
**Pull request by premalrupnur**
@nazrulhasan1 Pls link static files 
Files to be changed:
Experiments/theory
Experiments/references
Experiments/procedure
Experiments/simulation

### CODE REVIEW

**Comment by nazrulhasan1** [comment]
noice sirrr

**Comment by nazrulhasan1** [comment]
there will be some issues like i wont be able to run the server you would
have to personally check whether will it run or not

**Comment by nazrulhasan1** [comment]
@premalrupnur `Well i have done my part please check whether it is working alright or not`

**Comment by premalrupnur** [comment]
Ok will check it out

**Comment by nazrulhasan1** [comment]
Great, thanks!

**Pull request merged**
